import './styles.css';
import './sync.css';
import { DECKS, GUIDE, TESTS, CHEM_SHAPES } from './library.js';
import { $, esc, icon, INK, BLUE, MUTED, line, txt, circ, path, note, svg, FIGURES, figure } from './diagrams.js';
import { createSyncUI } from './sync-ui.js';

// Course-aware study state; the old biology card IDs remain unchanged.
const ALL=DECKS.flatMap(d=>d.cards), CARD_MAP=new Map(ALL.map(c=>[c.id,c])), TEST_MAP=new Map(TESTS.map(t=>[t.id,t]));
const QA=new URLSearchParams(location.search).has('qa');
const STORE=QA?'molecule-study-hosted-qa':'molecule-study-guest-v1';
let syncUI=null;
const MODE_NAMES={flashcards:'Flashcards',swipe:'Swipe review',test:'Test',wrong:'Wrong deck',diagrams:'Diagram lab',browse:'Browse cards'};
const COURSES=['BIOL 112','CHEM 121'];
const starIcon=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="m12 2.5 2.9 5.9 6.5.9-4.7 4.6 1.1 6.5-5.8-3.1-5.8 3.1 1.1-6.5L2.6 9.3l6.5-.9Z"/></svg>`;
let db={version:2,progress:{},activeTests:{},testHistory:[],settings:{deck:0}},storageOK=true;
function normalizeRecord(v){
 if(!v||typeof v!=='object'||!['new','practice','known'].includes(v.status)||!Number.isFinite(v.due)||v.due<0||!Number.isInteger(v.streak)||v.streak<0||v.streak>1000||typeof v.star!=='boolean')throw Error('Invalid card review data.');
 const ev=(v.history||[]);if(!Array.isArray(ev))throw Error('Invalid review history.');
 const history=ev.slice(-40).map(h=>{if(!h||typeof h.ok!=='boolean'||!Number.isFinite(h.at)||typeof h.source!=='string')throw Error('Invalid review event.');return {at:h.at,ok:h.ok,source:h.source.slice(0,60),chosen:String(h.chosen||'').slice(0,2500),expected:String(h.expected||'').slice(0,2500)}});
 const misses=Number.isInteger(v.misses)&&v.misses>=0?v.misses:(v.status==='practice'?1:0);
 const lastWrong=v.lastWrong&&typeof v.lastWrong==='object'?{at:Number(v.lastWrong.at)||0,source:String(v.lastWrong.source||'Previous review').slice(0,60),chosen:String(v.lastWrong.chosen||'Forgot').slice(0,2500),expected:String(v.lastWrong.expected||'').slice(0,2500)}:null;
 return {status:v.status,due:v.due,streak:v.streak,star:v.star,misses,history,lastWrong};
}
function validSession(s){
 if(!s||typeof s!=='object'||!Array.isArray(s.items)||!s.items.length||s.items.length>100||!Number.isInteger(s.pos)||s.pos<0||s.pos>s.items.length||!Number.isFinite(s.created))return false;
 return s.items.every(i=>{const q=TEST_MAP.get(i.id);return q&&Array.isArray(i.options)&&i.options.length===q.options.length&&new Set(i.options).size===q.options.length&&i.options.every(o=>q.options.includes(o))&&(i.choice===null||i.options.includes(i.choice))&&typeof i.checked==='boolean'&&(!i.checked||i.choice!==null)});
}
try{
 const raw=localStorage.getItem(STORE);
 if(raw){const data=JSON.parse(raw);if(data.version!==2)throw Error('Unknown data version.');for(const[id,v]of Object.entries(data.progress||{}))if(CARD_MAP.has(id))db.progress[id]=normalizeRecord(v);for(const[k,s]of Object.entries(data.activeTests||{}))if(COURSES.includes(k)&&validSession(s))db.activeTests[k]=s;db.testHistory=Array.isArray(data.testHistory)?data.testHistory.filter(h=>h&&COURSES.includes(h.course)&&Number.isFinite(h.at)&&Number.isInteger(h.total)&&Number.isInteger(h.correct)&&h.total>0&&h.correct>=0&&h.correct<=h.total).slice(-60):[];if(Number.isInteger(data.settings?.deck)&&DECKS[data.settings.deck])db.settings.deck=data.settings.deck;}
 
}catch(e){storageOK=false}
let state={deck:db.settings.deck,tab:'flashcards',filter:'all',queue:[],pos:0,revealed:false,search:'',kind:'all',lab:'ester',annotations:false,wrongFilter:'active',reviewIds:null,testScope:'set',testLength:10,openCourse:DECKS[db.settings.deck].course};
state.lab=state.deck<4?['ester','nucleotide','bilayer','hydrophobic'][state.deck]:'v-ax4';
function record(id){return db.progress[id]||{status:'new',due:0,streak:0,star:false,misses:0,history:[],lastWrong:null}}
function save(){try{if(!syncUI?.isSignedIn())localStorage.setItem(STORE,JSON.stringify(db));syncUI?.capture(db)}catch(e){storageOK=false}$('#storage-warning').hidden=storageOK}
function unitCards(){return ALL.filter(c=>DECKS[c.deck].course===DECKS[state.deck].course)}
function wrongCards(all=false){return unitCards().filter(c=>all?record(c.id).misses>0:record(c.id).status==='practice')}
function shuffled(xs){let a=[...xs];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
let toastTimer;
function toast(msg){$('#toast').textContent=msg;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3000)}
function matches(c){let r=record(c.id);return state.filter==='all'||state.filter==='due'&&(r.status==='new'||r.due<=Date.now())||state.filter==='practice'&&r.status==='practice'||state.filter==='starred'&&r.star||state.filter==='custom'}
function rebuild(){const pool=state.reviewIds?state.reviewIds.map(id=>CARD_MAP.get(id)).filter(Boolean):DECKS[state.deck].cards;state.queue=pool.filter(matches).map(c=>c.id);state.pos=0;state.revealed=false}
function current(){return CARD_MAP.get(state.queue[state.pos])}
function mark(c,ok,source,chosen=''){
 const old=record(c.id),at=Date.now(),streak=ok?Math.min(old.streak+1,1000):0;
 const event={at,ok,source,chosen:chosen||(ok?'Remembered':'Forgot'),expected:c.back};
 db.progress[c.id]={...old,status:ok?'known':'practice',streak,due:at+(ok?[1,3,7,14,30][Math.min(streak-1,4)]*86400000:600000),misses:old.misses+(ok?0:1),history:[...old.history,event].slice(-40),lastWrong:ok?old.lastWrong:event};save();
}
function updateShell(){
 const unit=DECKS[state.deck],activeWrong=wrongCards().length;
 $('#decks').innerHTML=COURSES.map(course=>`<section class="course-section ${state.openCourse!==course?'closed':''}"><button class="course-heading" data-course="${course}" aria-expanded="${state.openCourse===course}"><span>${course}</span><span aria-hidden="true">${state.openCourse===course?'−':'+'}</span></button><span class="unit-name">${course==='BIOL 112'?'Macromolecules':'VSEPR theory'}</span><div class="unit-decks">${DECKS.map((d,i)=>d.course===course?`<button class="deck ${i===state.deck?'active':''}" data-deck="${i}" ${i===state.deck?'aria-current="page"':''}><span class="deck-num">${String(i%4+1).padStart(2,'0')}</span><span>${esc(d.title)}</span></button>`:'').join('')}</div></section>`).join('');
 $('#deck-title').textContent=unit.title;
 $('#breadcrumbs').innerHTML=`<span>${unit.course}</span><span>${unit.unit}</span>`;
 $('#unit-description').textContent=unit.course==='BIOL 112'?'From your September 18 & 21 notes · '+unit.cards.length+' cards':'From your four VSEPR tables · '+unit.cards.length+' cards';
 $('#mode-tabs').innerHTML=Object.entries(MODE_NAMES).map(([id,name])=>`<button class="tab ${state.tab===id?'active':''}" id="tab-${id}" role="tab" aria-selected="${state.tab===id}" aria-controls="panel" tabindex="${state.tab===id?0:-1}" data-tab="${id}">${name}${id==='wrong'?` <small>${activeWrong}</small>`:''}</button>`).join('');
 $('#panel').setAttribute('aria-labelledby','tab-'+state.tab);$('#storage-warning').hidden=storageOK;
}
function render(){updateShell();({flashcards:renderCards,swipe:renderCards,test:renderTest,wrong:renderWrong,diagrams:renderLab,browse:renderBrowse})[state.tab]()}
function selectDeck(i){state.deck=i;db.settings.deck=i;state.openCourse=DECKS[i].course;state.reviewIds=null;state.filter='all';state.search='';state.kind='all';state.lab=i<4?['ester','nucleotide','bilayer','hydrophobic'][i]:'v-ax4';state.annotations=false;rebuild();save();render()}
function setTab(tab){state.tab=tab;if(tab==='swipe'||tab==='flashcards'){state.revealed=false}render()}
function cardGraphic(c,back=false){if(!c.figure)return '';if(back)return figure(c.figure,false);const f=FIGURES[c.figure];return `<div class="figure">${svg(f.draw(false),f.desc,c.figure.startsWith('v-')?'170 0 380 300':undefined)}</div><p class="figure-caption">${c.deck>=4?'A = central atom · blue X = attached atom · gold pair = lone pair':'Simplified diagram; some hydrogens and substituents are omitted.'}</p>`}
function filterOptions(){const options=[['all','All cards'],['due','Due + new'],['practice','Needs practice'],['starred','Favorites · 收藏']];if(state.reviewIds)options.push(['custom','Wrong-deck session']);return options.map(([v,t])=>`<option value="${v}" ${v===state.filter?'selected':''}>${t}</option>`).join('')}
function renderCards(){
 const c=current(),n=state.queue.length,swipe=state.tab==='swipe';
 let s=`<div class="toolbar"><label class="visually-hidden" for="queue-filter">Review queue</label><select id="queue-filter" class="control">${filterOptions()}</select><button id="shuffle" class="secondary blue" ${n<2?'disabled':''}>${icon('shuffle')}Shuffle</button><span class="count">${n} ${n===1?'card':'cards'}</span></div>`;
 if(!c){s+=`<div class="empty"><h2>${n?'Session complete':'Nothing in this queue yet'}</h2><p>${n?'Your ratings have been saved. Revisit the wrong-question deck to practice anything you forgot.':state.filter==='starred'?'Tap the star at the bottom of a card to save it here.':state.filter==='practice'?'Cards you forget or miss in a test will appear here.':'No cards are due in this selection. You can still study all cards.'}</p><button id="restart-all" class="primary">Study all cards</button><button id="open-wrong" class="secondary">Open wrong deck</button></div>`}
 else{
 s+=`<p class="mode-note">${swipe?'← Forgot goes to your wrong deck · Remembered goes right →':'Think of your answer, then click the card to flip it.'}</p><div class="drag-wrap" id="drag-wrap"><div class="flip-scene" id="flip-scene"><div class="swipe-stamp left">Forgot</div><div class="swipe-stamp right">Remembered</div><div class="flip-card ${state.revealed?'is-flipped':''}" id="flip-card"><article class="card-face front" aria-label="Card front" aria-hidden="${state.revealed}" ${state.revealed?'inert':''}><div class="card-meta"><span class="kind">${esc(c.kind)}</span><span class="card-status">FRONT</span></div><div class="card-content"><h2 class="question">${esc(c.prompt)}</h2>${cardGraphic(c)}</div><p class="flip-hint">Click or press Space to flip</p></article><article class="card-face back" aria-label="Card back" aria-hidden="${!state.revealed}" ${!state.revealed?'inert':''}><div class="card-meta"><span class="kind">${esc(c.concept)}</span><span class="card-status">BACK</span></div><div class="card-content"><p class="question">${esc(c.prompt)}</p><div class="answer">${esc(c.back)}</div>${c.figure?`<div class="answer-context">${esc(FIGURES[c.figure].explain)}</div>`:''}</div><p class="flip-hint">Click or press Space to see the question again</p></article></div></div></div><div class="card-footer"><button id="favorite" class="star-button" aria-pressed="${record(c.id).star}" aria-label="${record(c.id).star?'Remove favorite':'Add favorite'}">${starIcon}<span>${record(c.id).star?'Saved · 已收藏':'Favorite · 收藏'}</span></button><button id="flip" class="quiet">${state.revealed?'Show front':'Flip to answer'} ↻</button></div><div class="rating-bar"><button id="forgot" class="secondary forgot" ${!swipe&&!state.revealed?'disabled':''}>← Forgot</button><button id="remembered" class="secondary remember" ${!swipe&&!state.revealed?'disabled':''}>Remembered →</button></div>`;
 }
 s+=`<div class="session-nav"><button id="previous" class="circle" aria-label="Previous card" ${state.pos===0?'disabled':''}>${icon('left',22)}</button><div class="session-text"><strong>${c?`Card ${state.pos+1} of ${n}`:n?'End of session':'Recall first. Reveal second.'}</strong><small>${swipe?'Drag left or right, or use the buttons.':'Space flips · 1 Forgot · 2 Remembered'}</small></div><button id="next" class="circle" aria-label="Skip card" ${!c?'disabled':''}>${icon('right',22)}</button></div><div class="progress" role="progressbar" aria-label="Session position" aria-valuemin="0" aria-valuemax="${Math.max(n,1)}" aria-valuenow="${Math.min(state.pos,n)}"><span style="width:${n?Math.min(state.pos/n*100,100):0}%"></span></div><div class="below"><span>${wrongCards().length} need review in ${DECKS[state.deck].unit} · ${syncUI?.isSignedIn()?'automatic sync enabled':'saved on this device'}</span><button class="quiet" id="show-source">Study tips & backups</button></div>`;
 $('#panel').innerHTML=s;
}
function flip(){if(!current()||!['flashcards','swipe'].includes(state.tab))return;state.revealed=!state.revealed;const card=$('#flip-card');card.classList.toggle('is-flipped',state.revealed);for(const[sel,hide]of [['.front',state.revealed],['.back',!state.revealed]]){const face=card.querySelector(sel);face.setAttribute('aria-hidden',hide);face.inert=hide}$('#flip').textContent=state.revealed?'Show front ↻':'Flip to answer ↻';if(state.tab==='flashcards'){for(const id of ['forgot','remembered'])$('#'+id).disabled=!state.revealed}}
function next(){if(state.pos<state.queue.length){state.pos++;state.revealed=false;renderCards()}}
let ratingBusy=false;
function rate(ok,animate=false){const c=current();if(!c||ratingBusy||state.tab==='flashcards'&&!state.revealed)return;ratingBusy=true;mark(c,ok,state.tab==='swipe'?'Swipe review':'Flashcards');const finish=()=>{state.pos++;state.revealed=false;ratingBusy=false;render();toast(ok?'Remembered · review scheduled':'Saved to wrong deck · '+c.concept)};if(animate){const wrap=$('#drag-wrap');wrap.classList.add('departing');wrap.style.transform=`translateX(${ok?280:-280}px) rotate(${ok?12:-12}deg)`;setTimeout(finish,180)}else finish()}
function toggleFavorite(){const c=current();if(!c)return;db.progress[c.id]={...record(c.id),star:!record(c.id).star};save();const b=$('#favorite');b.setAttribute('aria-pressed',record(c.id).star);b.setAttribute('aria-label',record(c.id).star?'Remove favorite':'Add favorite');b.querySelector('span').textContent=record(c.id).star?'Saved · 已收藏':'Favorite · 收藏'}
function reviewWrong(){state.reviewIds=wrongCards(state.wrongFilter==='history').map(c=>c.id);state.filter='custom';state.tab='swipe';rebuild();render()}
function studyCard(id){const c=CARD_MAP.get(id);if(!c)return;state.deck=c.deck;state.openCourse=DECKS[c.deck].course;state.reviewIds=null;state.filter='all';state.tab='flashcards';rebuild();state.pos=state.queue.indexOf(id);render()}
function renderWrong(){const rows=wrongCards(state.wrongFilter==='history'),concepts=new Set(rows.map(c=>c.concept));$('#panel').innerHTML=`<div class="wrong-overview"><div><strong>Wrong questions · 错题本</strong><p>${rows.length} ${rows.length===1?'card':'cards'} · ${concepts.size} knowledge ${concepts.size===1?'point':'points'}</p></div><button id="practice-wrong" class="primary" ${rows.length?'':'disabled'}>Practice these</button></div><div class="toolbar"><label for="wrong-filter" class="visually-hidden">Mistake history filter</label><select id="wrong-filter" class="control"><option value="active" ${state.wrongFilter==='active'?'selected':''}>Needs review</option><option value="history" ${state.wrongFilter==='history'?'selected':''}>All missed · history</option></select><span class="hint">Across ${DECKS[state.deck].course} → ${DECKS[state.deck].unit}</span></div>${rows.length?rows.sort((a,b)=>(record(b.id).lastWrong?.at||0)-(record(a.id).lastWrong?.at||0)).map(c=>{let r=record(c.id),w=r.lastWrong;return `<article class="wrong-row"><div><span class="concept-label">${esc(c.concept)}</span><p class="wrong-front">${esc(c.front)}</p></div><button class="secondary" data-study="${c.id}">Review</button><p class="meta">${r.misses} ${r.misses===1?'miss':'misses'} · ${esc(DECKS[c.deck].title)} · <span class="${r.status==='practice'?'':'resolved'}">${r.status==='practice'?'Needs review':'Resolved; history kept'}</span></p><details><summary>See my mistake & correct answer</summary><p><strong>Your last miss:</strong> ${esc(w?.chosen||'Forgot during an earlier review')}</p><p><strong>Correct answer:</strong> ${esc(c.back)}</p><p>${esc(w?.source||'Previous review')}${w?.at?' · '+new Date(w.at).toLocaleString():''}</p>${r.history.slice(-5).reverse().map(h=>`<div class="history-item">${h.ok?'✓ Correct / remembered':'✕ Missed / forgot'} · ${esc(h.source)} · ${new Date(h.at).toLocaleString()}</div>`).join('')}</details></article>`}).join(''):`<div class="empty"><h2>No ${state.wrongFilter==='history'?'recorded mistakes':'questions to revisit'}</h2><p>A wrong test answer or a left swipe saves the question and its concept here automatically.</p><button id="open-test" class="primary">Try a test</button></div>`}`}
function testKey(){return DECKS[state.deck].course}
function session(){return db.activeTests[testKey()]}
function testPool(){const ds=DECKS[state.deck];return TESTS.filter(q=>DECKS[q.deck].course===ds.course&&(state.testScope==='set'?q.deck===state.deck:state.testScope==='wrong'?record(q.cardId).status==='practice':true))}
function renderTest(){
 const s=session();if(!s){const n=testPool().length;$('#panel').innerHTML=`<div class="test-setup"><h2>Test what you know.</h2><p class="mode-note">Answer-key scoring. Every incorrect answer records the question, your choice, and its knowledge point in your wrong deck.</p><div class="test-form"><label class="field">Question source<select id="test-scope" class="control"><option value="set" ${state.testScope==='set'?'selected':''}>This set</option><option value="unit" ${state.testScope==='unit'?'selected':''}>Whole unit</option><option value="wrong" ${state.testScope==='wrong'?'selected':''}>Wrong questions only</option></select></label><label class="field">Test length<select id="test-length" class="control">${[5,10,20].map(x=>`<option value="${x}" ${state.testLength===x?'selected':''}>${x} questions</option>`).join('')}</select></label></div><p class="status-note">${n} curated multiple-choice questions available. This test will use ${Math.min(n,state.testLength)}.</p><button id="start-test" class="primary" ${n?'':'disabled'}>Start test</button>${!n?'<p class="notice">No scored questions match this selection yet. You can still practice every missed flashcard in Wrong deck.</p>':''}</div>${historyHTML()}`;return}
 if(s.pos>=s.items.length){renderResultsTest(s);return}
 const item=s.items[s.pos],q=TEST_MAP.get(item.id),c=CARD_MAP.get(q.cardId),right=item.choice===q.options[0];
 $('#panel').innerHTML=`<div class="toolbar"><span class="status-note">${s.pos+1} / ${s.items.length} · ${esc(DECKS[q.deck].title)}</span><span class="count">${s.items.filter(i=>i.checked&&i.choice===TEST_MAP.get(i.id).options[0]).length} correct so far</span></div><article class="test-question"><span class="kind">${item.checked?esc(q.concept):'Knowledge check'}</span><h2>${esc(q.prompt)}</h2>${q.figure?cardGraphic(c):''}<div class="choices" role="group" aria-label="Answer choices">${item.options.map((option,i)=>`<button class="choice ${item.choice===option?'selected':''} ${item.checked?(option===q.options[0]?'correct':option===item.choice?'incorrect':''):''}" data-choice="${i}" aria-pressed="${item.choice===option}" ${item.checked?'disabled':''}><span class="letter">${'ABCD'[i]}</span><span>${esc(option)}</span></button>`).join('')}</div>${item.checked?`<div class="feedback ${right?'':'incorrect'}" role="status"><strong>${right?'Correct.':'Saved to your wrong deck.'}</strong>${esc(q.explanation)}${!right?`<br><strong>Correct choice: ${esc(q.options[0])}</strong>`:''}</div>`:''}<div class="test-actions"><span class="hint">${item.checked?'Knowledge point: '+esc(q.concept):'Choose one answer before checking.'}</span><button class="primary" id="${item.checked?'test-next':'check-answer'}" ${item.choice===null?'disabled':''}>${item.checked?(s.pos===s.items.length-1?'See results':'Next question'):'Check answer'}</button></div></article><p class="status-note">This test is saved as you go. You can return to another study mode and resume here.</p>`;
}
function historyHTML(){const h=db.testHistory.filter(h=>h.course===testKey()).slice(-5).reverse();return h.length?`<div class="test-history"><strong>Recent tests</strong>${h.map(t=>`<div>${new Date(t.at).toLocaleString()} · ${t.correct}/${t.total} correct</div>`).join('')}</div>`:''}
function startTest(){const pool=shuffled(testPool()).slice(0,state.testLength);if(!pool.length)return;db.activeTests[testKey()]={created:Date.now(),items:pool.map(q=>({id:q.id,options:shuffled(q.options),choice:null,checked:false})),pos:0,logged:false};save();renderTest()}
function chooseAnswer(index){const s=session(),i=s?.items[s.pos];if(!i||i.checked||!Number.isInteger(index)||!i.options[index])return;i.choice=i.options[index];save();renderTest()}
function checkAnswer(){const s=session(),i=s?.items[s.pos];if(!i||i.checked||i.choice===null)return;const q=TEST_MAP.get(i.id);i.checked=true;mark(CARD_MAP.get(q.cardId),i.choice===q.options[0],'Test',i.choice);save();updateShell();renderTest()}
function testNext(){const s=session();if(!s||!s.items[s.pos]?.checked)return;s.pos++;if(s.pos>=s.items.length&&!s.logged){s.logged=true;db.testHistory.push({course:testKey(),at:Date.now(),correct:s.items.filter(i=>i.choice===TEST_MAP.get(i.id).options[0]).length,total:s.items.length});db.testHistory=db.testHistory.slice(-60)}save();renderTest()}
function renderResultsTest(s){const correct=s.items.filter(i=>i.choice===TEST_MAP.get(i.id).options[0]).length;$('#panel').innerHTML=`<div class="test-summary"><h2>Test complete</h2><div class="score">${correct} / ${s.items.length}</div><p class="mode-note">${s.items.length-correct} ${s.items.length-correct===1?'miss was':'misses were'} recorded with your selected answer and the correct explanation.</p><div class="dialog-actions"><button id="open-wrong" class="primary">Review wrong questions</button><button id="new-test" class="secondary">New test</button></div></div>${s.items.map((i,n)=>{const q=TEST_MAP.get(i.id),ok=i.choice===q.options[0];return `<details class="result-row"><summary><span class="result-status ${ok?'':'miss'}">${ok?'✓ Correct':'✕ Missed'}</span>${n+1}. ${esc(q.prompt)}</summary><p><strong>Your answer:</strong> ${esc(i.choice)}</p><p><strong>Correct:</strong> ${esc(q.options[0])}</p><p>${esc(q.explanation)}</p><p>Knowledge point: ${esc(q.concept)}</p><button class="secondary" data-study="${q.cardId}">Review flashcard</button></details>`}).join('')}`}

// VSEPR schematics project ideal domain vectors. Gold pairs are never counted as X atoms.
function shapeVectors(n){if(n===2)return [[-1,0,0],[1,0,0]];if(n===3)return [[0,1,0],[-.866,-.5,0],[.866,-.5,0]];if(n===4)return [[0,1,0],[-.943,-.333,0],[.471,-.333,.816],[.471,-.333,-.816]];if(n===5)return [[0,1,0],[0,-1,0],[-1,0,0],[.5,0,.866],[.5,0,-.866]];if(n===6)return [[0,1,0],[0,-1,0],[-1,0,0],[1,0,0],[0,0,1],[0,0,-1]];return [[0,1,0],[0,-1,0],...Array.from({length:5},(_,i)=>[Math.cos(Math.PI+i*2*Math.PI/5),0,Math.sin(Math.PI+i*2*Math.PI/5)])]}
function vseprDiagram(shape,annotated){const vectors=shapeVectors(shape.n),lpOrder=shape.n===4?[0,1]:shape.n===5?[4,3,2]:shape.n===6?[1,0]:[0];const lp=new Set(lpOrder.slice(0,shape.e));const project=v=>[360+(v[0]+v[2]*(shape.n===4?0:shape.n===6?.75:.37))*118,140+(-v[1]+v[2]*(shape.n===4?.25:shape.n===6?.6:.57))*101];let bonds='',atoms='';vectors.map((v,i)=>({v,i})).sort((a,b)=>a.v[2]-b.v[2]).forEach(({v,i})=>{const [x,y]=project(v);if(lp.has(i)){const px=360+(x-360)*.71,py=140+(y-140)*.71;bonds+=`<line x1="360" y1="140" x2="${px}" y2="${py}" stroke="#c99727" stroke-width="2" stroke-dasharray="4 5"/>`;atoms+=`<ellipse cx="${px}" cy="${py}" rx="22" ry="15" fill="#fff3ce" stroke="#e5bc5e"/>`+circ(px-6,py,3.5,'#a77413')+circ(px+6,py,3.5,'#a77413');if(annotated)atoms+=txt(px+(px>360?31:-31),py,'E',15,'#a77413');}else{const dash=v[2]<-.2?' stroke-dasharray="3 5"':'';bonds+=`<line x1="360" y1="140" x2="${x}" y2="${y}" stroke="${v[2]<-.2?'#95accd':'#627caa'}" stroke-width="${v[2]>.2?7:3.5}"${dash}/>`;atoms+=circ(x,y,17,v[2]<-.2?'#739ee8':BLUE)+txt(x,y+1,'X',17,'white')}});let center=circ(360,140,22,INK)+txt(360,141,'A',20,'white');return bonds+atoms+center+(annotated?note(360,274,`${shape.formula} · X = ${shape.x} · E = ${shape.e} · E + X = ${shape.n}`):'')}
for(const s of CHEM_SHAPES){FIGURES['v-'+s.key]={name:s.formula+' · '+s.name,group:s.parent+' parent',caption:'Perspective projection. Blue X = attached atom; gold dots = lone pair. Do not measure angles from this drawing.',desc:`Central A with ${s.x} attached X atoms and ${s.e} lone pairs; solid bonds come forward and dashed bonds go back.`,explain:`${s.formula}: ${s.x} attached atoms + ${s.e} lone pairs = ${s.n} domains. Parent: ${s.parent}. Molecular shape: ${s.name}. Your table lists approximately ${s.angles}.`,draw:a=>vseprDiagram(s,a)}}
function renderLab(){const isChem=state.deck>=4,entries=Object.entries(FIGURES).filter(([k])=>isChem?k.startsWith('v-'):!k.startsWith('v-'));if(!entries.some(([k])=>k===state.lab))state.lab=entries[0][0];let groups='',prev='';for(const[k,f]of entries){if(f.group!==prev){groups+=`<h3>${esc(f.group)}</h3>`;prev=f.group}groups+=`<button data-figure="${k}" class="${k===state.lab?'active':''}" aria-pressed="${k===state.lab}">${esc(f.name)}</button>`}const f=FIGURES[state.lab];$('#panel').innerHTML=`<p class="status-note">${isChem?'Compare all 14 configurations from your tables. Parent shape counts X + E; molecular shape names the X arrangement.':'Compare the structures, then identify them from memory in Flashcards.'}</p><div class="lab-layout"><nav class="figure-menu" aria-label="Choose a diagram">${groups}</nav><div class="lab-stage"><h2>${esc(f.name)}</h2>${figure(state.lab,state.annotations)}<button id="annotations" class="secondary" aria-pressed="${state.annotations}">${state.annotations?'Hide':'Show'} annotations</button><div class="annotation"><strong>What to notice</strong><p>${esc(f.explain)}</p></div></div></div>`}
function renderBrowse(){$('#panel').innerHTML=`<div class="toolbar"><label class="visually-hidden" for="search">Search this set</label><input id="search" class="control search" type="search" placeholder="Search questions, answers, or concepts…" value="${esc(state.search)}"><label class="visually-hidden" for="browse-filter">Browse filter</label><select id="browse-filter" class="control"><option value="all">All cards</option><option value="starred" ${state.kind==='starred'?'selected':''}>Favorites · 收藏</option></select></div><p id="browse-count" class="status-note"></p><div class="browse-list" id="browse-results"></div>`;renderBrowseResults()}
function renderBrowseResults(){const q=state.search.toLocaleLowerCase().trim(),rows=DECKS[state.deck].cards.filter(c=>(state.kind!=='starred'||record(c.id).star)&&(!q||(c.front+' '+c.back+' '+c.concept).toLocaleLowerCase().includes(q)));$('#browse-count').textContent=`${rows.length} cards · open a question to see its answer`;$('#browse-results').innerHTML=rows.length?rows.map(c=>`<div class="card-row"><details><summary>${esc(c.front)}</summary><p>${esc(c.back)}</p></details><button class="secondary" data-study="${c.id}">Study</button><span class="row-meta">${esc(c.concept)}${record(c.id).star?' · ★ 收藏':''}</span></div>`).join(''):'<div class="empty"><h2>No matching cards</h2><p>Try a shorter term or a different filter.</p></div>'}
function download(name,content,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)}
function exportDeck(i){const unit=DECKS[state.deck],cs=i==='master'?unitCards():DECKS[Number(i)].cards;download(i==='master'?(unit.course==='BIOL 112'?'BIOL_Macromolecules_Master.txt':'CHEM121_VSEPR_Master.txt'):DECKS[Number(i)].file,cs.map(c=>c.front+'\t'+c.back).join('\n')+'\n')}
function exportOpen(){$('#export-heading').textContent=DECKS[state.deck].course+' · '+DECKS[state.deck].unit;$('#export-list').innerHTML=DECKS.map((d,i)=>d.course===DECKS[state.deck].course?`<div class="download-row"><span>${esc(d.title)}<br><small class="hint">${d.cards.length} cards</small></span><button class="secondary" data-download="${i}">Download .txt</button></div>`:'').join('')+`<div class="download-row"><strong>Unit master · ${unitCards().length} cards</strong><button class="primary" data-download="master">Download all</button></div>`;$('#export-dialog').showModal()}

let pointer=null,suppressClickUntil=0;
document.addEventListener('pointerdown',e=>{if(state.tab!=='swipe'||!current()||!e.target.closest('#flip-scene')||ratingBusy||e.button!==0)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,dx:0,dy:0};$('#flip-scene').setPointerCapture(e.pointerId)});
document.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;pointer.dx=e.clientX-pointer.x;pointer.dy=e.clientY-pointer.y;if(Math.abs(pointer.dx)>Math.abs(pointer.dy)*1.2&&Math.abs(pointer.dx)>10){const w=$('#drag-wrap');w.classList.add('dragging');w.style.transform=`translateX(${pointer.dx*.7}px) rotate(${pointer.dx*.025}deg)`;$('.swipe-stamp.left').style.opacity=pointer.dx<0?Math.min(Math.abs(pointer.dx)/90,1):0;$('.swipe-stamp.right').style.opacity=pointer.dx>0?Math.min(pointer.dx/90,1):0;if(e.cancelable)e.preventDefault()}});
function finishPointer(e,cancel=false){if(!pointer||pointer.id!==e.pointerId)return;const p=pointer;pointer=null;const w=$('#drag-wrap');if(!w)return;w.classList.remove('dragging');if(!cancel&&Math.abs(p.dx)>75&&Math.abs(p.dx)>Math.abs(p.dy)*1.2){suppressClickUntil=Date.now()+500;rate(p.dx>0,true)}else{w.style.transform='';document.querySelectorAll('.swipe-stamp').forEach(x=>x.style.opacity=0);if(Math.abs(p.dx)>10||Math.abs(p.dy)>10)suppressClickUntil=Date.now()+500}}
document.addEventListener('pointerup',e=>finishPointer(e));document.addEventListener('pointercancel',e=>finishPointer(e,true));
document.addEventListener('click',e=>{
 if(e.target.closest('#flip-scene')){if(Date.now()>suppressClickUntil)flip();return}
 const b=e.target.closest('button');if(!b)return;
 if(b.dataset.course){const course=b.dataset.course;if(DECKS[state.deck].course!==course)selectDeck(course==='BIOL 112'?0:4);else{state.openCourse=state.openCourse===course?'':course;updateShell()}return}
 if(b.dataset.deck!==undefined){selectDeck(Number(b.dataset.deck));return}
 if(b.dataset.tab){setTab(b.dataset.tab);return}
 if(b.dataset.figure){state.lab=b.dataset.figure;renderLab();return}
 if(b.dataset.study){studyCard(b.dataset.study);return}
 if(b.dataset.choice!==undefined){chooseAnswer(Number(b.dataset.choice));return}
 if(b.dataset.download!==undefined){exportDeck(b.dataset.download);return}
 if(b.classList.contains('close')){b.closest('dialog').close();return}
 const actions={flip,favorite:toggleFavorite,forgot:()=>rate(false,state.tab==='swipe'),remembered:()=>rate(true,state.tab==='swipe'),next,previous:()=>{if(state.pos>0){state.pos--;state.revealed=false;renderCards()}},shuffle:()=>{state.queue=shuffled(state.queue);state.pos=0;state.revealed=false;renderCards();toast('Queue shuffled')},'restart-all':()=>{state.filter='all';state.reviewIds=null;rebuild();renderCards()},'open-wrong':()=>setTab('wrong'),'practice-wrong':reviewWrong,'open-test':()=>setTab('test'),'start-test':startTest,'check-answer':checkAnswer,'test-next':testNext,'new-test':()=>{delete db.activeTests[testKey()];save();renderTest()},annotations:()=>{state.annotations=!state.annotations;renderLab()},'export-open':exportOpen,'guide-open':()=>$('#guide-dialog').showModal(),'show-source':()=>$('#guide-dialog').showModal(),'guide-download':()=>download('BIOL_Macromolecules_Active_Recall.md',GUIDE),'backup-export':()=>{download('Course_Practice_Progress.json',JSON.stringify({...db,exported:new Date().toISOString()},null,2),'application/json');$('#backup-message').textContent='Backup downloaded, including mistakes, favorites and tests.'}};
 if(actions[b.id])actions[b.id]();
});
document.addEventListener('change',e=>{const id=e.target.id,v=e.target.value;if(id==='queue-filter'){state.filter=v;if(v!=='custom')state.reviewIds=null;rebuild();renderCards()}else if(id==='wrong-filter'){state.wrongFilter=v;renderWrong()}else if(id==='browse-filter'){state.kind=v;renderBrowseResults()}else if(id==='test-scope'){state.testScope=v;renderTest()}else if(id==='test-length'){state.testLength=Number(v);renderTest()}});
document.addEventListener('input',e=>{if(e.target.id==='search'){state.search=e.target.value;renderBrowseResults()}});
document.addEventListener('keydown',e=>{
 if(e.target.closest('[role="tablist"]')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const tabs=Object.keys(MODE_NAMES),idx=tabs.indexOf(state.tab);setTab(tabs[(idx+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length]);$('#tab-'+state.tab).focus();return}
 if(!['flashcards','swipe'].includes(state.tab)||$('dialog[open]')||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey||e.repeat)return;
 if(e.key===' '){if(e.target.closest('button')&&e.target.id!=='flip')return;e.preventDefault();flip()}
 else if(e.key==='1')rate(false,state.tab==='swipe');else if(e.key==='2')rate(true,state.tab==='swipe');else if(e.key==='ArrowRight'){e.preventDefault();state.tab==='swipe'?rate(true,true):next()}else if(e.key==='ArrowLeft'){e.preventDefault();if(state.tab==='swipe')rate(false,true);else if(state.pos>0){state.pos--;state.revealed=false;renderCards()}}
});
$('#backup-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{
 if(f.size>4000000)throw Error('Choose a progress backup smaller than 4 MB.');
 const data=JSON.parse(await f.text());if(![1,2].includes(data.version)||!data.progress||typeof data.progress!=='object'||Array.isArray(data.progress))throw Error('This is not a compatible progress backup.');
 const imported={version:2,progress:{},activeTests:{},testHistory:[],settings:db.settings};
 for(const[id,v]of Object.entries(data.progress))if(CARD_MAP.has(id))imported.progress[id]=normalizeRecord(v);
 for(const[k,s]of Object.entries(data.activeTests||{}))if(COURSES.includes(k)&&validSession(s))imported.activeTests[k]=s;
 imported.testHistory=(data.testHistory||[]).filter(h=>h&&COURSES.includes(h.course)&&Number.isFinite(h.at)&&Number.isInteger(h.total)&&Number.isInteger(h.correct)&&h.total>0&&h.correct>=0&&h.correct<=h.total);
 if(syncUI?.isSignedIn())await syncUI.importBackup(imported);
 else{for(const[id,v]of Object.entries(imported.progress))if(!db.progress[id])db.progress[id]=v;for(const[k,s]of Object.entries(imported.activeTests))if(!db.activeTests[k])db.activeTests[k]=s;db.testHistory.push(...imported.testHistory);save();rebuild();render()}
 $('#backup-message').textContent='Backup imported. Existing card progress is kept; missing cards are added.';
 }catch(err){$('#backup-message').textContent=err.message||'Could not read this backup.'}finally{e.target.value=''}});
function replaceAccountData(data){
 const next={version:2,progress:{},activeTests:{},testHistory:[],settings:db.settings};
 for(const[id,v]of Object.entries(data.progress||{}))if(CARD_MAP.has(id)){try{next.progress[id]=normalizeRecord(v)}catch{}}
 for(const[k,s]of Object.entries(data.activeTests||{}))if(COURSES.includes(k)&&validSession(s))next.activeTests[k]=s;
 next.testHistory=(data.testHistory||[]).filter(h=>h&&COURSES.includes(h.course)&&Number.isFinite(h.at)&&Number.isInteger(h.total)&&Number.isInteger(h.correct)&&h.total>0&&h.correct>=0&&h.correct<=h.total).slice(-60);
 db=next;updateShell();
 // Preserve the open flashcard, its side, and text-input focus during background sync.
 if(['wrong','test'].includes(state.tab)&&!document.querySelector('dialog[open]'))render();
 else if(state.tab==='browse')renderBrowseResults();
 else if(['flashcards','swipe'].includes(state.tab)&&current()){
   const button=$('#favorite'),saved=record(current().id).star;if(button){button.setAttribute('aria-pressed',saved);button.setAttribute('aria-label',saved?'Remove favorite':'Add favorite');button.querySelector('span').textContent=saved?'Saved · 已收藏':'Favorite · 收藏'}
 }
}
rebuild();render();
syncUI=createSyncUI({getData:()=>db,onData:replaceAccountData,getGuest:()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}},onAccountSwitch:data=>{replaceAccountData(data);rebuild();render()},qa:QA});
