import {validateImage} from './notebook-media.js';
import {emptyNotebook,questionStats,issueStats,addAttempt} from './notebook-core.js';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={unresolved:'还没弄懂',reviewing:'巩固中',mastered:'已掌握'};
export function createNotebookUI({getData,getCourse,getChapters,save,getMedia,getOwner=()=>null,getIllustration=()=>''}){
 let view='all',search='',chapter='',concept='',reason='',status='',lastCourse='';
 const dialog=document.createElement('dialog');dialog.className='notebook-dialog';document.body.append(dialog);
 const n=()=>getData().notebook??(getData().notebook=emptyNotebook());
 const options=(xs,value,all)=>`<option value="">${all}</option>`+xs.map(x=>`<option ${value===x?'selected':''} value="${escape(x)}">${escape(x)}</option>`).join('');
 function edit(q){
  const course=getCourse(),owner=getOwner(),issues=Object.values(n().issues).filter(i=>i.course===course);
  const chapters=[...new Set([...getChapters(course),...(course==='BIOL 112'?['MLM1 test']:[]),...Object.values(n().chapters||{}).filter(c=>c.course===course).map(c=>c.title),...Object.values(n().questions).filter(x=>x.course===course).map(x=>x.chapter)])];
  const concepts=[...(q?.concepts||[])],known=[...new Set(Object.values(n().questions).filter(x=>x.course===course).flatMap(x=>x.concepts))];
  let images=(q?.images||[]).map(image=>({image})),busy=false,closed=false;
  dialog.innerHTML=`<form id="notebook-form"><h2>${q?'编辑错题':'记录一道错题'} · ${course}</h2><section class="notebook-upload" aria-label="题目与截图"><label>题目（文字可选）<textarea name="prompt" maxlength="8000" placeholder="输入题目，或直接粘贴 / 添加截图">${escape(q?.prompt)}</textarea></label><label class="notebook-file-label">＋ 添加截图<input type="file" name="images" accept="image/png,image/jpeg,image/webp,image/gif" multiple></label><p class="notebook-help">可在此粘贴截图（⌘V / Ctrl+V），或拖入图片。最多 6 张，每张 5 MB；点击图片可放大。</p><div class="notebook-images" id="notebook-image-previews"></div></section><label>正确答案<textarea name="answer" maxlength="8000">${escape(q?.answer)}</textarea></label>${q?'':'<label>我的错误回答<textarea name="chosen" maxlength="8000"></textarea></label>'}<label>所属章节<select name="chapter" required>${options(chapters,q?.chapter,'请选择章节')}<option value="__add_chapter__">＋ 增加选项</option></select></label><div id="notebook-new-chapter" hidden><label>新章节名称<input name="newChapter" maxlength="150" placeholder="例如：MLM2 test"></label><div class="notebook-inline"><button type="button" class="secondary" data-add-chapter>添加并选中</button><button type="button" class="quiet" data-cancel-chapter>取消新增</button></div></div><fieldset><legend>知识点</legend><div id="notebook-concept-tags" class="notebook-tags"></div><div class="notebook-inline"><label class="notebook-grow">搜索或添加知识点<input name="conceptSearch" maxlength="150" placeholder="一次输入一个，例如：Ion–PD" autocomplete="off"></label><button type="button" class="secondary" data-add-concept>添加</button></div><div id="notebook-concept-options" class="notebook-tags" aria-label="已有知识点"></div><p class="notebook-help">选择已有标签，或输入一个知识点后按 Enter。知识点写「考什么」，具体的错误想法放在复盘中。</p></fieldset><label>错因<input name="reason" maxlength="150" value="${escape(q?.reason||'待分析')}" placeholder="例如：漏看条件、结构识别"></label><fieldset><legend>关联共性问题（可跨章节）</legend>${issues.length?issues.map(i=>`<label class="notebook-check"><input type="checkbox" name="issue" value="${i.id}" ${q?.issueIds.includes(i.id)?'checked':''}>${escape(i.title)}</label>`).join(''):'先在「按共性问题」中新建一个问题，再回来关联。'}</fieldset><label>个人解析 / 复盘<textarea name="notes" maxlength="8000">${escape(q?.notes)}</textarea></label><p class="notebook-error" role="status" aria-live="polite"></p><div class="dialog-actions"><button class="primary" data-save>保存</button><button type="button" class="secondary" data-cancel>取消</button></div></form>`;
  const form=dialog.querySelector('form'),message=dialog.querySelector('.notebook-error'),chapterSelect=form.elements.chapter,searchInput=form.elements.conceptSearch;
  const say=text=>message.textContent=text,canonical=value=>value.trim().replace(/\s+/g,' '),same=(a,b)=>a.toLocaleLowerCase()===b.toLocaleLowerCase();
  function addChapter(){if(getOwner()!==owner){say('账号已切换，请重新打开错题。');return false}const value=canonical(form.elements.newChapter.value);if(!value){say('请输入章节名称。');return false}const title=chapters.find(c=>same(c,value))||value;if(!chapters.includes(title)){const id=crypto.randomUUID();n().chapters??={};n().chapters[id]={id,course,title,updatedAt:Date.now()};chapters.push(title);save()}chapterSelect.innerHTML=options(chapters,title,'请选择章节')+'<option value="__add_chapter__">＋ 增加选项</option>';dialog.querySelector('#notebook-new-chapter').hidden=true;form.elements.newChapter.value='';say('');return true}
  chapterSelect.onchange=()=>{const adding=chapterSelect.value==='__add_chapter__';dialog.querySelector('#notebook-new-chapter').hidden=!adding;if(adding)form.elements.newChapter.focus()};
  dialog.querySelector('[data-add-chapter]').onclick=addChapter;
  form.elements.newChapter.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();if(!e.isComposing)addChapter()}};
  dialog.querySelector('[data-cancel-chapter]').onclick=()=>{chapterSelect.value=q?.chapter||'';dialog.querySelector('#notebook-new-chapter').hidden=true};
  function renderConcepts(){dialog.querySelector('#notebook-concept-tags').innerHTML=concepts.map((c,i)=>`<button class="notebook-tag selected" type="button" data-remove-concept="${i}" aria-label="移除知识点 ${escape(c)}">${escape(c)} <span aria-hidden="true">×</span></button>`).join('');const matches=known.filter(c=>!concepts.some(x=>same(c,x))&&c.toLocaleLowerCase().includes(searchInput.value.trim().toLocaleLowerCase())).slice(0,12);dialog.querySelector('#notebook-concept-options').innerHTML=matches.map(c=>`<button class="notebook-tag" type="button" data-pick-concept="${escape(c)}">＋ ${escape(c)}</button>`).join('');dialog.querySelectorAll('[data-remove-concept]').forEach(b=>b.onclick=()=>{concepts.splice(Number(b.dataset.removeConcept),1);renderConcepts()});dialog.querySelectorAll('[data-pick-concept]').forEach(b=>b.onclick=()=>addConcept(b.dataset.pickConcept))}
  function addConcept(value=searchInput.value){value=canonical(value);if(!value)return;if(concepts.length>=50){say('最多选择 50 个知识点。');return}value=known.find(c=>same(c,value))||value;if(!concepts.some(c=>same(c,value)))concepts.push(value);searchInput.value='';renderConcepts()}
  searchInput.oninput=renderConcepts;searchInput.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();if(!e.isComposing)addConcept()}};dialog.querySelector('[data-add-concept]').onclick=()=>addConcept();renderConcepts();
  function previewImages(){const root=dialog.querySelector('#notebook-image-previews');root.innerHTML=images.map((item,i)=>`<figure><button type="button" class="notebook-image-open" data-stage-image="${i}" aria-label="放大截图 ${i+1}"><img alt="题目截图 ${i+1}" ${item.url?`src="${escape(item.url)}"`:''}></button><figcaption>${escape(item.file?.name||item.image.name)}</figcaption><div class="notebook-inline"><button type="button" class="quiet" data-replace-image="${i}">替换</button><button type="button" class="quiet" data-remove-image="${i}">移除</button></div></figure>`).join('');images.forEach((item,i)=>{if(!item.url)getMedia().url(item.image).then(url=>{if(!closed&&images[i]===item){item.url=url;root.querySelector(`[data-stage-image="${i}"] img`).src=url}}).catch(e=>say(e.message))});root.querySelectorAll('[data-stage-image]').forEach(b=>b.onclick=()=>{const item=images[Number(b.dataset.stageImage)];if(item.url)showImage(item.url)});root.querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>{const [item]=images.splice(Number(b.dataset.removeImage),1);if(item.file)URL.revokeObjectURL(item.url);previewImages()});root.querySelectorAll('[data-replace-image]').forEach(b=>b.onclick=()=>{const index=Number(b.dataset.replaceImage),input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,image/gif';input.onchange=()=>addImages(input.files,index);input.click()})}
  async function addImages(files,replace){if(busy)return;busy=true;const added=[];dialog.querySelector('[data-save]').disabled=true;try{for(const file of Array.from(files)){validateImage(file);const bitmap=await createImageBitmap(file);bitmap.close();added.push({file,url:URL.createObjectURL(file)})}if(closed){added.forEach(i=>URL.revokeObjectURL(i.url));return}if(images.length+(replace===undefined?added.length:0)>6){added.forEach(i=>URL.revokeObjectURL(i.url));throw Error('同一道题最多添加 6 张截图。')}if(replace!==undefined&&added.length){const old=images[replace];if(old.file)URL.revokeObjectURL(old.url);images.splice(replace,1,added[0])}else images.push(...added);say('');previewImages()}catch(e){for(const item of added)if(!images.includes(item))URL.revokeObjectURL(item.url);say(e.message||'无法读取这张图片。')}finally{busy=false;dialog.querySelector('[data-save]').disabled=false;form.elements.images.value=''}}
  form.elements.images.onchange=e=>addImages(e.target.files);
  const upload=dialog.querySelector('.notebook-upload');upload.onpaste=e=>{const files=Array.from(e.clipboardData?.files||[]);if(files.length){e.preventDefault();addImages(files)}};upload.ondragover=e=>{e.preventDefault();upload.classList.add('dragging')};upload.ondragleave=()=>upload.classList.remove('dragging');upload.ondrop=e=>{e.preventDefault();upload.classList.remove('dragging');addImages(e.dataTransfer.files)};previewImages();
  dialog.oncancel=e=>{if(busy)e.preventDefault()};
  dialog.onclose=()=>{closed=true;for(const item of images)if(item.file)URL.revokeObjectURL(item.url)};
  dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();
  form.onsubmit=async e=>{e.preventDefault();if(busy)return;if(getOwner()!==owner){say('账号已切换，请重新打开错题。');return}if(chapterSelect.value==='__add_chapter__'&&!addChapter())return;addConcept();const f=new FormData(form),prompt=f.get('prompt').trim();if(!prompt&&!images.length){say('请填写题目或添加至少一张截图。');return}busy=true;form.querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=true);say('正在保存…');try{const savedImages=[];for(const item of images){item.image??=await getMedia().upload(item.file);savedImages.push(item.image)}if(getOwner()!==owner)throw Error('账号已切换，请重新打开错题。');const at=Date.now(),id=q?.id||crypto.randomUUID();n().questions[id]={id,course,sourceCardId:q?.sourceCardId||'',illustration:q?.illustration||'',prompt,images:savedImages,answer:f.get('answer').trim(),chapter:f.get('chapter'),concepts:[...concepts],reason:f.get('reason').trim(),issueIds:f.getAll('issue'),notes:f.get('notes').trim(),createdAt:q?.createdAt||at,updatedAt:at};if(!q)addAttempt(n(),n().questions[id],false,f.get('chosen'),'手动录题',at);save();dialog.close();render()}catch(error){say(error.message||'保存失败，请重试。')}finally{busy=false;form.querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=false)}};dialog.showModal();
 }
 function editIssue(issue){
  dialog.onclose=null;dialog.oncancel=null;
  dialog.innerHTML=`<form><h2>${issue?'共性问题复盘':'新建共性问题'}</h2><label>问题名称<input name="title" required maxlength="150" value="${escape(issue?.title)}" placeholder="例如：忘记识别 radical"></label><label>统一总结<textarea name="summary" maxlength="8000" placeholder="识别线索、纠正方法、下次检查步骤…">${escape(issue?.summary)}</textarea></label><label>置顶到章节（每行一个章节名）<textarea name="pinnedChapters" placeholder="Chapter 2">${escape((issue?.pinnedChapters||[]).join('\n'))}</textarea></label><div class="dialog-actions"><button class="primary">保存</button><button type="button" class="secondary" data-cancel>取消</button></div></form>`;
  dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),title=f.get('title').trim();if(!title)return;const id=issue?.id||crypto.randomUUID();n().issues[id]={id,course:getCourse(),title,summary:f.get('summary').trim(),pinnedChapters:[...new Set(f.get('pinnedChapters').split(/\n/).map(x=>x.trim()).filter(Boolean))],updatedAt:Date.now()};save();dialog.close();render()};dialog.showModal();
 }
 function showImage(url){const viewer=document.createElement('dialog');viewer.className='notebook-image-viewer';const button=document.createElement('button');button.textContent='关闭大图';button.className='secondary';button.onclick=()=>viewer.close();const img=document.createElement('img');img.src=url;img.alt='题目截图原图';viewer.append(button,img);document.body.append(viewer);viewer.onclose=()=>viewer.remove();viewer.showModal()}
 function questionImages(q){return `<div class="notebook-images">${(q.images||[]).map((image,i)=>`<figure><button type="button" class="notebook-image-open" data-image-question="${q.id}" data-image-index="${i}" aria-label="放大截图 ${i+1}"><img alt="题目截图 ${i+1}"></button><figcaption>${escape(image.name)}<span class="notebook-image-status" role="status">加载中…</span></figcaption></figure>`).join('')}</div>`}
 function loadImages(root){root.querySelectorAll('[data-image-question]').forEach(button=>{const image=n().questions[button.dataset.imageQuestion]?.images?.[Number(button.dataset.imageIndex)],status=button.parentElement.querySelector('.notebook-image-status');if(!image)return;const load=()=>{status.textContent='加载中…';getMedia().url(image).then(url=>{if(!button.isConnected)return;button.querySelector('img').src=url;status.textContent='';button.onclick=()=>showImage(url)}).catch(e=>{if(!button.isConnected)return;status.textContent=e.message+' 点击重试';button.onclick=load})};load()})}
 function row(q){const s=questionStats(n(),q);return `<article class="notebook-question"><div class="notebook-meta">${escape(q.chapter)} · ${escape(q.concepts.join(' / '))}</div><h3>${escape(q.prompt||'截图题目')}</h3>${getIllustration(q)}${questionImages(q)}<p>${labels[s.status]} · 实际出错 ${s.misses} 次 · ${new Date(s.recent).toLocaleString()}${s.status==='reviewing'?' · 答对后 1 天再复习':''}</p><details><summary>查看答案、复盘与记录</summary><p class="notebook-copy"><b>正确答案：</b>${escape(q.answer||'尚未填写')}</p>${/^chem-ch2-(boron|resonance|chlorate|methanol|ammonium)$/.test(q.illustration)?`<figure class="notebook-structure"><a href="/notebook-structures/${q.illustration}.svg" target="_blank" rel="noopener" aria-label="查看结构大图"><img src="/notebook-structures/${q.illustration}.svg" alt="${escape(q.prompt)} — 解答结构示意图" loading="lazy"></a><figcaption>解答结构示意图 · 点击查看大图，核对电荷与孤对电子</figcaption></figure>`:''}<p><b>错因：</b>${escape(q.reason||'待分析')}</p><p class="notebook-copy">${escape(q.notes)}</p>${q.issueIds.map(id=>n().issues[id]).filter(i=>i?.course===q.course).map(i=>`<div class="notebook-shared"><b>${escape(i.title)}</b><p class="notebook-copy">${escape(i.summary||'尚未总结')}</p></div>`).join('')}<ol>${s.events.slice().reverse().map(a=>`<li>${a.ok?'答对':'答错'} · ${new Date(a.at).toLocaleString()} · ${escape(a.source)}${a.chosen?`<p>${escape(a.chosen)}</p>`:''}</li>`).join('')}</ol></details><div class="notebook-actions"><button class="secondary" data-edit="${q.id}">编辑 / 关联知识点</button><button class="secondary" data-review="${q.id}" data-ok="false">复习再次答错</button><button class="primary" data-review="${q.id}" data-ok="true">复习答对</button></div></article>`}
 function chapterOverview(c){const pinned=Object.values(n().issues).filter(i=>i.course===getCourse()&&i.pinnedChapters?.includes(c));return pinned.length?`<section class="notebook-chapter-overview" aria-label="章节常见问题"><h3>${escape(c)} · 常见问题</h3><ol>${pinned.map(i=>`<li><strong>${escape(i.title)}</strong><p class="notebook-copy">${escape(i.summary)}</p></li>`).join('')}</ol></section>`:''}
 function render(){
  const root=document.querySelector('#panel'),course=getCourse();if(lastCourse!==course){search=chapter=concept=reason=status='';lastCourse=course}
  const all=Object.values(n().questions).filter(q=>q.course===course),issues=Object.values(n().issues).filter(i=>i.course===course);
  const rows=all.filter(q=>(!search||(q.prompt+' '+q.answer).toLowerCase().includes(search.toLowerCase()))&&(!chapter||q.chapter===chapter)&&(!concept||q.concepts.includes(concept))&&(!reason||q.reason===reason)&&(!status||questionStats(n(),q).status===status)&&(view!=='due'||questionStats(n(),q).due)).sort((a,b)=>questionStats(n(),b).recent-questionStats(n(),a).recent);
  root.innerHTML=`<div class="notebook-heading"><div><h2>${course} · 错题本</h2><p>做题错误与复盘 · ${all.length} 道题 · ${all.reduce((v,q)=>v+questionStats(n(),q).misses,0)} 次实际出错</p></div><button id="notebook-add" class="primary">＋ 记录错题</button></div><nav class="notebook-tabs" aria-label="错题本视图">${[['all','全部'],['chapters','按章节'],['issues','按共性问题'],['due','待复习']].map(([v,t])=>`<button class="secondary ${view===v?'selected':''}" data-view="${v}" aria-pressed="${view===v}">${t}</button>`).join('')}</nav><p class="status-note">${view==='due'?'尚未弄懂和再次答错的题立即出现；反复出错的题答对后，1 天再复习。':'四个视图共用同一份错题记录。Test 答错自动记录；Forgot / 左滑进入「未记牢卡片」。'}</p>${view==='issues'?'<button id="notebook-issue-add" class="secondary">＋ 新建共性问题</button>':`<div class="notebook-filters"><label>搜索题目<input type="search" id="notebook-search" value="${escape(search)}" placeholder="题目或答案"></label><label>章节<select data-filter="chapter">${options([...new Set(all.map(q=>q.chapter))],chapter,'所有章节')}</select></label><label>知识点<select data-filter="concept">${options([...new Set(all.flatMap(q=>q.concepts))],concept,'所有知识点')}</select></label><label>错因<select data-filter="reason">${options([...new Set(all.map(q=>q.reason).filter(Boolean))],reason,'所有错因')}</select></label><label>掌握状态<select data-filter="status"><option value="">所有状态</option>${Object.entries(labels).map(([v,t])=>`<option value="${v}" ${status===v?'selected':''}>${t}</option>`).join('')}</select></label></div>`}${view!=='chapters'&&view!=='issues'?(chapter?chapterOverview(chapter):[...new Set(all.map(q=>q.chapter))].length===1?chapterOverview(all[0]?.chapter):''):''}<div id="notebook-rows">${view==='issues'?issues.map(i=>{const s=issueStats(n(),i);return `<section class="notebook-issue"><h3>${escape(i.title)}</h3><p>关联 ${s.count} 道题 · 实际出错 ${s.misses} 次</p><p class="notebook-copy">${escape(i.summary||'还没有统一总结。')}</p><button class="secondary" data-issue-edit="${i.id}">编辑统一总结</button>${s.questions.map(row).join('')}</section>`}).join('')||'<p class="empty">创建一个共性问题，再在错题编辑页关联它。</p>':rows.length?(view==='chapters'?[...new Set(rows.map(q=>q.chapter))].map(c=>`<section><h3 class="notebook-chapter">${escape(c)}</h3>${chapterOverview(c)}${rows.filter(q=>q.chapter===c).map(row).join('')}</section>`).join(''):rows.map(row).join('')):'<p class="empty">暂无符合条件的错题。可以记录错题，或完成一次 Test。</p>'}</div>`;
  loadImages(root);
  root.querySelector('#notebook-add').onclick=()=>edit();root.querySelector('#notebook-issue-add')?.addEventListener('click',()=>editIssue());
  root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
  root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(n().questions[b.dataset.edit]));
  root.querySelectorAll('[data-issue-edit]').forEach(b=>b.onclick=()=>editIssue(n().issues[b.dataset.issueEdit]));
  root.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{addAttempt(n(),n().questions[b.dataset.review],b.dataset.ok==='true');save();render()});
  root.querySelectorAll('[data-filter]').forEach(el=>el.onchange=()=>{({chapter:v=>chapter=v,concept:v=>concept=v,reason:v=>reason=v,status:v=>status=v})[el.dataset.filter](el.value);render()});
  root.querySelector('#notebook-search')?.addEventListener('input',e=>{search=e.target.value;const pos=e.target.selectionStart;render();const input=root.querySelector('#notebook-search');input.focus();try{input.setSelectionRange(pos,pos)}catch{}});
 }
 return {render,isEditing:()=>dialog.open};
}
