import {emptyNotebook,questionStats,issueStats,addAttempt} from './notebook-core.js';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={unresolved:'还没弄懂',reviewing:'巩固中',mastered:'已掌握'};
export function createNotebookUI({getData,getCourse,getChapters,save,getIllustration=()=>''}){
 let view='all',search='',chapter='',concept='',reason='',status='',lastCourse='';
 const dialog=document.createElement('dialog');dialog.className='notebook-dialog';document.body.append(dialog);
 const n=()=>getData().notebook??(getData().notebook=emptyNotebook());
 const options=(xs,value,all)=>`<option value="">${all}</option>`+xs.map(x=>`<option ${value===x?'selected':''} value="${escape(x)}">${escape(x)}</option>`).join('');
 function edit(q){
  const course=getCourse(),issues=Object.values(n().issues).filter(i=>i.course===course),chapters=[...new Set([...getChapters(course),...(q?[q.chapter]:[])])];
  dialog.innerHTML=`<form id="notebook-form"><h2>${q?'编辑错题':'记录一道错题'} · ${course}</h2><label>题目<textarea name="prompt" required maxlength="8000">${escape(q?.prompt)}</textarea></label><label>正确答案<textarea name="answer" maxlength="8000">${escape(q?.answer)}</textarea></label>${q?'':'<label>我的错误回答<textarea name="chosen" maxlength="8000"></textarea></label>'}<label>所属章节<select name="chapter" required>${options(chapters,q?.chapter,'请选择章节')}</select></label><label>知识点（用逗号分隔）<input name="concepts" maxlength="2000" value="${escape(q?.concepts.join(', '))}"></label><label>错因<input name="reason" maxlength="150" value="${escape(q?.reason||'待分析')}" placeholder="例如：漏看条件、结构识别"></label><fieldset><legend>关联共性问题（可跨章节）</legend>${issues.length?issues.map(i=>`<label class="notebook-check"><input type="checkbox" name="issue" value="${i.id}" ${q?.issueIds.includes(i.id)?'checked':''}>${escape(i.title)}</label>`).join(''):'先在「按共性问题」中新建一个问题，再回来关联。'}</fieldset><label>个人解析 / 复盘<textarea name="notes" maxlength="8000">${escape(q?.notes)}</textarea></label><div class="dialog-actions"><button class="primary">保存</button><button type="button" class="secondary" data-cancel>取消</button></div></form>`;
  dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();
  dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),at=Date.now(),id=q?.id||crypto.randomUUID();n().questions[id]={id,course,sourceCardId:q?.sourceCardId||'',prompt:f.get('prompt').trim(),answer:f.get('answer').trim(),chapter:f.get('chapter'),concepts:[...new Set(f.get('concepts').split(/[,，]/).map(x=>x.trim()).filter(Boolean))],reason:f.get('reason').trim(),issueIds:f.getAll('issue'),notes:f.get('notes').trim(),createdAt:q?.createdAt||at,updatedAt:at};if(!n().questions[id].prompt)return;if(!q)addAttempt(n(),n().questions[id],false,f.get('chosen'),'手动录题',at);save();dialog.close();render()};dialog.showModal();
 }
 function editIssue(issue){
  dialog.innerHTML=`<form><h2>${issue?'共性问题复盘':'新建共性问题'}</h2><label>问题名称<input name="title" required maxlength="150" value="${escape(issue?.title)}" placeholder="例如：忘记识别 radical"></label><label>统一总结<textarea name="summary" maxlength="8000" placeholder="识别线索、纠正方法、下次检查步骤…">${escape(issue?.summary)}</textarea></label><div class="dialog-actions"><button class="primary">保存</button><button type="button" class="secondary" data-cancel>取消</button></div></form>`;
  dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),title=f.get('title').trim();if(!title)return;const id=issue?.id||crypto.randomUUID();n().issues[id]={id,course:getCourse(),title,summary:f.get('summary').trim(),updatedAt:Date.now()};save();dialog.close();render()};dialog.showModal();
 }
 function row(q){const s=questionStats(n(),q);return `<article class="notebook-question"><div class="notebook-meta">${escape(q.chapter)} · ${escape(q.concepts.join(' / '))}</div><h3>${escape(q.prompt)}</h3>${getIllustration(q)}<p>${labels[s.status]} · 实际出错 ${s.misses} 次 · ${new Date(s.recent).toLocaleString()}${s.status==='reviewing'?' · 答对后 1 天再复习':''}</p><details><summary>查看答案、复盘与记录</summary><p class="notebook-copy"><b>正确答案：</b>${escape(q.answer||'尚未填写')}</p><p><b>错因：</b>${escape(q.reason||'待分析')}</p><p class="notebook-copy">${escape(q.notes)}</p>${q.issueIds.map(id=>n().issues[id]).filter(i=>i?.course===q.course).map(i=>`<div class="notebook-shared"><b>${escape(i.title)}</b><p class="notebook-copy">${escape(i.summary||'尚未总结')}</p></div>`).join('')}<ol>${s.events.slice().reverse().map(a=>`<li>${a.ok?'答对':'答错'} · ${new Date(a.at).toLocaleString()} · ${escape(a.source)}${a.chosen?`<p>${escape(a.chosen)}</p>`:''}</li>`).join('')}</ol></details><div class="notebook-actions"><button class="secondary" data-edit="${q.id}">编辑 / 关联知识点</button><button class="secondary" data-review="${q.id}" data-ok="false">复习再次答错</button><button class="primary" data-review="${q.id}" data-ok="true">复习答对</button></div></article>`}
 function render(){
  const root=document.querySelector('#panel'),course=getCourse();if(lastCourse!==course){search=chapter=concept=reason=status='';lastCourse=course}
  const all=Object.values(n().questions).filter(q=>q.course===course),issues=Object.values(n().issues).filter(i=>i.course===course);
  const rows=all.filter(q=>(!search||(q.prompt+' '+q.answer).toLowerCase().includes(search.toLowerCase()))&&(!chapter||q.chapter===chapter)&&(!concept||q.concepts.includes(concept))&&(!reason||q.reason===reason)&&(!status||questionStats(n(),q).status===status)&&(view!=='due'||questionStats(n(),q).due)).sort((a,b)=>questionStats(n(),b).recent-questionStats(n(),a).recent);
  root.innerHTML=`<div class="notebook-heading"><div><h2>${course} · 错题本</h2><p>做题错误与复盘 · ${all.length} 道题 · ${all.reduce((v,q)=>v+questionStats(n(),q).misses,0)} 次实际出错</p></div><button id="notebook-add" class="primary">＋ 记录错题</button></div><nav class="notebook-tabs" aria-label="错题本视图">${[['all','全部'],['chapters','按章节'],['issues','按共性问题'],['due','待复习']].map(([v,t])=>`<button class="secondary ${view===v?'selected':''}" data-view="${v}" aria-pressed="${view===v}">${t}</button>`).join('')}</nav><p class="status-note">${view==='due'?'尚未弄懂和再次答错的题立即出现；反复出错的题答对后，1 天再复习。':'四个视图共用同一份错题记录。Test 答错自动记录；Forgot / 左滑进入「未记牢卡片」。'}</p>${view==='issues'?'<button id="notebook-issue-add" class="secondary">＋ 新建共性问题</button>':`<div class="notebook-filters"><label>搜索题目<input type="search" id="notebook-search" value="${escape(search)}" placeholder="题目或答案"></label><label>章节<select data-filter="chapter">${options([...new Set(all.map(q=>q.chapter))],chapter,'所有章节')}</select></label><label>知识点<select data-filter="concept">${options([...new Set(all.flatMap(q=>q.concepts))],concept,'所有知识点')}</select></label><label>错因<select data-filter="reason">${options([...new Set(all.map(q=>q.reason).filter(Boolean))],reason,'所有错因')}</select></label><label>掌握状态<select data-filter="status"><option value="">所有状态</option>${Object.entries(labels).map(([v,t])=>`<option value="${v}" ${status===v?'selected':''}>${t}</option>`).join('')}</select></label></div>`}<div id="notebook-rows">${view==='issues'?issues.map(i=>{const s=issueStats(n(),i);return `<section class="notebook-issue"><h3>${escape(i.title)}</h3><p>关联 ${s.count} 道题 · 实际出错 ${s.misses} 次</p><p class="notebook-copy">${escape(i.summary||'还没有统一总结。')}</p><button class="secondary" data-issue-edit="${i.id}">编辑统一总结</button>${s.questions.map(row).join('')}</section>`}).join('')||'<p class="empty">创建一个共性问题，再在错题编辑页关联它。</p>':rows.length?(view==='chapters'?[...new Set(rows.map(q=>q.chapter))].map(c=>`<section><h3 class="notebook-chapter">${escape(c)}</h3>${rows.filter(q=>q.chapter===c).map(row).join('')}</section>`).join(''):rows.map(row).join('')):'<p class="empty">暂无符合条件的错题。可以记录错题，或完成一次 Test。</p>'}</div>`;
  root.querySelector('#notebook-add').onclick=()=>edit();root.querySelector('#notebook-issue-add')?.addEventListener('click',()=>editIssue());
  root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
  root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(n().questions[b.dataset.edit]));
  root.querySelectorAll('[data-issue-edit]').forEach(b=>b.onclick=()=>editIssue(n().issues[b.dataset.issueEdit]));
  root.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{addAttempt(n(),n().questions[b.dataset.review],b.dataset.ok==='true');save();render()});
  root.querySelectorAll('[data-filter]').forEach(el=>el.onchange=()=>{({chapter:v=>chapter=v,concept:v=>concept=v,reason:v=>reason=v,status:v=>status=v})[el.dataset.filter](el.value);render()});
  root.querySelector('#notebook-search')?.addEventListener('input',e=>{search=e.target.value;const pos=e.target.selectionStart;render();const input=root.querySelector('#notebook-search');input.focus();try{input.setSelectionRange(pos,pos)}catch{}});
 }
 return {render,isEditing:()=>dialog.open};
}
